name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Avoid piling up duplicate runs on the same PR/branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  # Fast checks: tidy, fmt, vet, golangci-lint, race, coverage
  ci:
    name: Build & Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          check-latest: true

      # Prevent auto toolchain switching (e.g., from a stray toolchain directive)
      - name: Pin toolchain
        run: echo "GOTOOLCHAIN=local" >> $GITHUB_ENV

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.58.1

      - name: Clean Go build caches
        run: go clean -cache -modcache -testcache

      - name: Make ci
        run: make ci

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            coverage.out
            coverage.html

  # Live server integration test (hits /add over HTTP)
  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: ci
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          check-latest: true

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Integration test (spins server on 18080)
        run: make ci-full

      - name: Where am I?
        if: always()
        run: |
          echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
          pwd
          ls -la

      - name: Find log
        if: always()
        run: |
          echo "Listing potential log locations..."
          find "${GITHUB_WORKSPACE}" -maxdepth 2 -type f -name ".itest_server.log" -ls || true
          echo "--- tail ---"
          tail -n 50 "${GITHUB_WORKSPACE}/.itest_server.log" || true

      - name: Upload integration logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-logs
          path: |
            ${{ github.workspace }}/.itest_server.log
